export const FETCH_COINS_START = 'FETCH_COINS_START';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAIL = 'FETCH_COINS_FAIL;'

export const FETCH_COIN_START = 'FETCH_COIN_START';
export const FETCH_COIN_SUCCESS = 'FETCH_COIN_SUCCESS';
export const FETCH_COIN_FAIL = 'FETCH_COIN_FAIL;'